version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./uploads:/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/digital_library
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=/uploads
      - MAX_CONTENT_LENGTH=16777216
      - ML_MODELS_PATH=/app/ml/models
    depends_on:
      - db
      - redis
      - prometheus

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./app:/app
      - ./uploads:/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/digital_library
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_library
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: